// Code generated by "go-stringer -type=OptionSliceSeparator --trimprefix=@me -output common_enum_string.go -nametransform=lower -fromstringgenfn"; DO NOT EDIT.

package qs

import (
	"errors"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OptionSliceSeparatorUnspecified-0]
	_ = x[OptionSliceSeparatorNone-1]
	_ = x[OptionSliceSeparatorComma-2]
	_ = x[OptionSliceSeparatorSemicolon-3]
	_ = x[OptionSliceSeparatorSpace-4]
}

const _OptionSliceSeparator_name = "unspecifiednonecommasemicolonspace"

var _OptionSliceSeparator_index = [...]uint8{0, 11, 15, 20, 29, 34}

func (i OptionSliceSeparator) String() string {
	if i < 0 || i >= OptionSliceSeparator(len(_OptionSliceSeparator_index)-1) {
		return "OptionSliceSeparator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OptionSliceSeparator_name[_OptionSliceSeparator_index[i]:_OptionSliceSeparator_index[i+1]]
}
func OptionSliceSeparatorFromString(s string) (OptionSliceSeparator, error) {
	for i := 0; i < 5; i++ {
		if e := OptionSliceSeparator(i + 0); s == e.String() {
			return e, nil
		}
	}
	return OptionSliceSeparator(0), errors.New("cannot deternime OptionSliceSeparator from string")
}
