// Code generated by "go-stringer -type=UnmarshalPresence,UnmarshalSliceValues,UnmarshalSliceUnexpectedValue --trimprefix=@me -output unmarshal_enum_string.go -nametransform=lower -fromstringgenfn"; DO NOT EDIT.

package qs

import (
	"errors"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnmarshalPresenceUPUnspecified-0]
	_ = x[UnmarshalPresenceOpt-1]
	_ = x[UnmarshalPresenceNil-2]
	_ = x[UnmarshalPresenceReq-3]
}

const _UnmarshalPresence_name = "upunspecifiedoptnilreq"

var _UnmarshalPresence_index = [...]uint8{0, 13, 16, 19, 22}

func (i UnmarshalPresence) String() string {
	if i < 0 || i >= UnmarshalPresence(len(_UnmarshalPresence_index)-1) {
		return "UnmarshalPresence(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnmarshalPresence_name[_UnmarshalPresence_index[i]:_UnmarshalPresence_index[i+1]]
}
func UnmarshalPresenceFromString(s string) (UnmarshalPresence, error) {
	for i := 0; i < 4; i++ {
		if e := UnmarshalPresence(i + 0); s == e.String() {
			return e, nil
		}
	}
	return UnmarshalPresence(0), errors.New("cannot deternime UnmarshalPresence from string")
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnmarshalSliceValuesUPUnspecified-0]
	_ = x[UnmarshalSliceValuesKeepOld-1]
	_ = x[UnmarshalSliceValuesOverrideOld-2]
}

const _UnmarshalSliceValues_name = "upunspecifiedkeepoldoverrideold"

var _UnmarshalSliceValues_index = [...]uint8{0, 13, 20, 31}

func (i UnmarshalSliceValues) String() string {
	if i < 0 || i >= UnmarshalSliceValues(len(_UnmarshalSliceValues_index)-1) {
		return "UnmarshalSliceValues(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnmarshalSliceValues_name[_UnmarshalSliceValues_index[i]:_UnmarshalSliceValues_index[i+1]]
}
func UnmarshalSliceValuesFromString(s string) (UnmarshalSliceValues, error) {
	for i := 0; i < 3; i++ {
		if e := UnmarshalSliceValues(i + 0); s == e.String() {
			return e, nil
		}
	}
	return UnmarshalSliceValues(0), errors.New("cannot deternime UnmarshalSliceValues from string")
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnmarshalSliceUnexpectedValueUPUnspecified-0]
	_ = x[UnmarshalSliceUnexpectedValueBreakWithError-1]
	_ = x[UnmarshalSliceUnexpectedValueSkip-2]
}

const _UnmarshalSliceUnexpectedValue_name = "upunspecifiedbreakwitherrorskip"

var _UnmarshalSliceUnexpectedValue_index = [...]uint8{0, 13, 27, 31}

func (i UnmarshalSliceUnexpectedValue) String() string {
	if i < 0 || i >= UnmarshalSliceUnexpectedValue(len(_UnmarshalSliceUnexpectedValue_index)-1) {
		return "UnmarshalSliceUnexpectedValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnmarshalSliceUnexpectedValue_name[_UnmarshalSliceUnexpectedValue_index[i]:_UnmarshalSliceUnexpectedValue_index[i+1]]
}
func UnmarshalSliceUnexpectedValueFromString(s string) (UnmarshalSliceUnexpectedValue, error) {
	for i := 0; i < 3; i++ {
		if e := UnmarshalSliceUnexpectedValue(i + 0); s == e.String() {
			return e, nil
		}
	}
	return UnmarshalSliceUnexpectedValue(0), errors.New("cannot deternime UnmarshalSliceUnexpectedValue from string")
}
